name: RoyaleApp

options:
  bundleIdPrefix: nakandakari.toru.RoyaleApp
  deploymentTarget:
    iOS: 13.0
  developmentLanguage: en
  xcodeVersion: "12.0"
  # Carthage の実行パスを指定
  carthageExecutablePath: ./Scripts/Carthage/carthage.sh

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 2
    DEVELOPMENT_TEAM: 8CBGKNYH9U
    DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

configs:
  Debug: debug
  Release: release

configFiles:
  Debug: Configs/debug_config.xcconfig
  Release: Configs/release_config.xcconfig

settingGroups:
  RoyaleAppSettings:
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: 8CBGKNYH9U
    SWIFT_VERSION: 5.0    

targets:
  RoyaleApp:
    type: application
    platform: iOS
    sources: [RoyaleApp]
    settings:
      groups: [RoyaleAppSettings]
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: RoyaleApp_Development
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Dev
        Release:
          PROVISIONING_PROFILE_SPECIFIER: RoyaleApp_Production
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon          
      INFOPLIST_FILE: RoyaleApp/Info.plist
      OTHER_LDFLAGS: $(inherited)      
    dependencies:
      - target: Analytics    
      - target: DataStore
      - target: Domain
      - target: Presentation
    preBuildScripts:
      - path: ./Scripts/Google/copy_google_service_info_plist.sh
        name: Copy GoogleService-Info.plist  
    postCompileScripts:
      - path: ./Scripts/Swiftlint/swiftlint.sh
        name: Run SwiftLint
    postBuildScripts:
        - path: ./Scripts/FirebaseCrashlytics/firebase_crashlytics.sh
          name: Run Firebase Crashlytics
          inputFiles:
            - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
            - ${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}
        - path: ./Scripts/FirebaseCrashlytics/upload_dsyms.sh
          name: Upload dSYMs

  Analytics:
    type: framework
    platform: iOS
    sources: [Analytics]
    settings:
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: Analytics/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.Analytics
      SWIFT_VERSION: 5.0
      OTHER_LDFLAGS: -ObjC
      FRAMEWORK_SEARCH_PATHS:
        - $(inherited)
        - $(PROJECT_DIR)/Carthage/Build/iOS
    dependencies:
      - sdk: libc++.tbd
      - target: DataStore
      - target: Domain
      - carthage: FIRAnalyticsConnector
      - carthage: FirebaseAnalytics
      - carthage: FirebaseCore
      - carthage: FirebaseCoreDiagnostics
      - carthage: FirebaseCrashlytics
      - carthage: FirebaseInstallations
      - carthage: FirebaseRemoteConfig
      - carthage: GoogleAppMeasurement
      - carthage: GoogleDataTransport
      - carthage: GoogleUtilities
      - carthage: nanopb
      - carthage: PromisesObjC

  DataStore:
    type: framework
    platform: iOS
    sources: [DataStore]
    settings:
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: DataStore/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.DataStore
      SWIFT_VERSION: 5.0
      OTHER_LDFLAGS: -ObjC      
      LD_RUNPATH_SEARCH_PATHS: ${inherited} @executable_path/Frameworks @loader_path/Frameworks
    dependencies:
      - carthage: Alamofire
      - carthage: Realm
      - carthage: RealmSwift

  Domain:
    type: framework
    platform: iOS
    sources: [Domain]
    settings:
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: Domain/Info.plist      
      PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.Domain
      SWIFT_VERSION: 5.0      
    dependencies:
      - target: DataStore

  Presentation:
    type: framework
    platform: iOS    
    sources: [Presentation]
    dependencies:
      - target: Analytics
      - target: Domain
      - carthage: Charts
      - carthage: Kingfisher
      - carthage: SwipeableTabBarController
      - carthage: GoogleMobileAds
    settings:
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: Presentation/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.Presentation
      SWIFT_VERSION: 5.0
      OTHER_LDFLAGS: -ObjC
      LD_RUNPATH_SEARCH_PATHS: ${inherited} @executable_path/Frameworks @loader_path/Frameworks

schemes:
  RoyaleApp:
    build:
      targets:
        RoyaleApp: all
    run:
      config: Debug
      commandLineArguments:
        "-FIRDebugEnabled": false
        "-FIRDebugDisabled": true
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release