name: RoyaleApp

options:
  bundleIdPrefix: nakandakari.toru.RoyaleApp
  deploymentTarget:
    iOS: 13.0
  developmentLanguage: en
  xcodeVersion: "14.0"

settings:
  base:
    MARKETING_VERSION: 1.2.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: 8CBGKNYH9U
    DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    CODE_SIGN_STYLE: Manual
    SWIFT_VERSION: 5.0

configs:
  Debug: debug
  Release: release

configFiles:
  Debug: Configs/debug_config.xcconfig
  Release: Configs/release_config.xcconfig

packages: # SPM で扱うパッケージ
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    version: 9.6.0
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    version: 5.6.2
  SwipeableTabBarController:
    url: https://github.com/marcosgriselli/SwipeableTabBarController.git
    version: 3.4.2
  realm-swift:
    url: https://github.com/realm/realm-swift.git
    version: 10.29.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    version: 7.3.2
  Charts:
    url: https://github.com/danielgindi/Charts.git
    version: 4.1.0
  # Charts SDK のために必要
  Algorithms:
    url: https://github.com/apple/swift-algorithms
    version: 0.0.1


targets:
  RoyaleApp:
    type: application
    platform: iOS
    sources: [RoyaleApp]
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        INFOPLIST_FILE: RoyaleApp/Info.plist
        OTHER_LDFLAGS: $(inherited)
        OTHER_SWIFT_FLAGS: -Xfrontend -warn-long-function-bodies=300 -Xfrontend -debug-time-function-bodies -Xfrontend -warn-long-expression-type-checking=200"
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: RoyaleApp_Development
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-Dev
          CODE_SIGN_ENTITLEMENTS: RoyaleApp/RoyaleApp_Debug.entitlements
          PRODUCT_NAME: RoyaleApp
        Release:
          PROVISIONING_PROFILE_SPECIFIER: RoyaleApp_Production
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
          CODE_SIGN_ENTITLEMENTS: RoyaleApp/RoyaleApp_Release.entitlements
          PRODUCT_NAME: クラロワガイド

    dependencies:
      - target: Analytics    
      - target: DataStore
      - target: Domain
      - target: Presentation
      - target: RoyaleAppWidget
        codeSign: false
        embed: true

    preBuildScripts:
      - path: ./Scripts/Google/copy_google_service_info_plist.sh
        name: Copy GoogleService-Info.plist  
    postCompileScripts:
      - path: ./Scripts/Swiftlint/swiftlint.sh
        name: Run SwiftLint
    postBuildScripts:
        - path: ./Scripts/FirebaseCrashlytics/firebase_crashlytics.sh
          name: Run Firebase Crashlytics
          inputFiles:
            - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
            - ${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}
        - path: ./Scripts/FirebaseCrashlytics/upload_dsyms.sh
          name: Upload dSYMs

  Analytics:
    type: framework
    platform: iOS
    sources: [Analytics]
    settings:
      base:
        INFOPLIST_FILE: Analytics/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.Analytics
        OTHER_LDFLAGS: -ObjC
        OTHER_SWIFT_FLAGS: -Xfrontend -warn-long-function-bodies=300 -Xfrontend -debug-time-function-bodies -Xfrontend -warn-long-expression-type-checking=200"
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
    dependencies:
      - sdk: libc++.tbd
      - target: DataStore
      - target: Domain
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseRemoteConfig

  DataStore:
    type: framework
    platform: iOS
    sources: [DataStore]
    settings:
      base:
        INFOPLIST_FILE: DataStore/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.DataStore
        OTHER_LDFLAGS: -ObjC
        OTHER_SWIFT_FLAGS: -Xfrontend -warn-long-function-bodies=300 -Xfrontend -debug-time-function-bodies -Xfrontend -warn-long-expression-type-checking=200"
        LD_RUNPATH_SEARCH_PATHS: ${inherited} @executable_path/Frameworks @loader_path/Frameworks
        APPLICATION_EXTENSION_API_ONLY: YES # To use from widget-extension
    dependencies:
      - package: Alamofire
      - package: realm-swift

  Domain:
    type: framework
    platform: iOS
    sources: [Domain]
    settings:
      base:
        INFOPLIST_FILE: Domain/Info.plist      
        PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.Domain
        OTHER_SWIFT_FLAGS: -Xfrontend -warn-long-function-bodies=300 -Xfrontend -debug-time-function-bodies -Xfrontend -warn-long-expression-type-checking=200"
        APPLICATION_EXTENSION_API_ONLY: YES # To use from widget-extension
    dependencies:
      - target: DataStore

  Presentation:
    type: framework
    platform: iOS    
    sources: [Presentation]
    dependencies:
      - target: Analytics
      - target: Domain
      - package: Charts
      - package: Kingfisher
      - package: SwipeableTabBarController
      # - framework: Frameworks/GoogleMobileAds/GoogleMobileAds.xcframework
      - package: Algorithms
    settings:
      base:
        INFOPLIST_FILE: Presentation/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.Presentation
        OTHER_LDFLAGS: -ObjC
        OTHER_SWIFT_FLAGS: -Xfrontend -warn-long-function-bodies=300 -Xfrontend -debug-time-function-bodies -Xfrontend -warn-long-expression-type-checking=200"
        LD_RUNPATH_SEARCH_PATHS: ${inherited} @executable_path/Frameworks @loader_path/Frameworks

  RoyaleAppWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: 14.0
    sources: [RoyaleAppWidget]
    dependencies:
      - target: Domain
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
    settings:
      base:
        INFOPLIST_FILE: RoyaleAppWidget/Info.plist
        PRODUCT_NAME: "RoyaleAppWidgets"
        OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC
        OTHER_SWIFT_FLAGS: -Xfrontend -warn-long-function-bodies=300 -Xfrontend -debug-time-function-bodies -Xfrontend -warn-long-expression-type-checking=200"
        LD_RUNPATH_SEARCH_PATHS: 
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@executable_path/../../Frameworks"
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.RoyaleApp.dev.Widget
          PROVISIONING_PROFILE_SPECIFIER: RoyaleApp_Widget_Development
          CODE_SIGN_ENTITLEMENTS: RoyaleAppWidget/RoyaleAppWidgets_Debug.entitlements
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.RoyaleApp.Widget
          PROVISIONING_PROFILE_SPECIFIER: RoyaleApp_Widget_Production
          CODE_SIGN_ENTITLEMENTS: RoyaleAppWidget/RoyaleAppWidgets_Release.entitlements

schemes:
  RoyaleApp:
    build:
      targets:
        RoyaleApp: all
    run:
      config: Debug
      commandLineArguments:
        "-FIRDebugEnabled": false
        "-FIRDebugDisabled": true
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release