attributes:
  LastSwiftUpdateCheck: 1160
  LastUpgradeCheck: 1140
  ORGANIZATIONNAME: nakandakari
configs:
  Debug: debug
  Release: release
name: RoyaleApp
options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
settings:
  configs:
    Debug:
      IPHONEOS_DEPLOYMENT_TARGET: 13.0
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: YES
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      IPHONEOS_DEPLOYMENT_TARGET: 13.0
      MTL_FAST_MATH: YES
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  Analytics:
    dependencies:
    - target: DataStore
    - target: Domain
    platform: iOS
    settings:
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 8CBGKNYH9U
          FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/iOS
          INFOPLIST_FILE: Analytics/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: com.Analytics
          SWIFT_VERSION: 5.0
        Release:
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 8CBGKNYH9U
          FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/iOS
          INFOPLIST_FILE: Analytics/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: com.Analytics
          SWIFT_VERSION: 5.0
    sources: [Analytics]
    type: framework
  AnalyticsTests:
    dependencies:
    - target: Analytics
    - target: RoyaleApp
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: AnalyticsTests/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: com.AnalyticsTests
          SWIFT_VERSION: 5.0
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/RoyaleApp.app/RoyaleApp
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: AnalyticsTests/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: com.AnalyticsTests
          SWIFT_VERSION: 5.0
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/RoyaleApp.app/RoyaleApp
    sources: [AnalyticsTests]
    type: bundle.unit-test
  DataStore:
    dependencies:
    - framework: Carthage/Build/iOS/Alamofire.framework
    - framework: Realm.framework
    - framework: RealmSwift.framework
    platform: iOS
    settings:
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/iOS
          - $(PROJECT_DIR)
          INFOPLIST_FILE: DataStore/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.DataStore
          SWIFT_VERSION: 5.0
        Release:
          CODE_SIGN_STYLE: Automatic
          FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/iOS
          - $(PROJECT_DIR)
          INFOPLIST_FILE: DataStore/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.DataStore
          SWIFT_VERSION: 5.0
    sources: [DataStore]
    type: framework
  DataStoreTests:
    dependencies:
    - target: DataStore
    - target: RoyaleApp
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: DataStoreTests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.DataStoreTests
          SWIFT_VERSION: 5.0
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/RoyaleApp.app/RoyaleApp
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: DataStoreTests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.DataStoreTests
          SWIFT_VERSION: 5.0
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/RoyaleApp.app/RoyaleApp
    sources: [DataStoreTests]
    type: bundle.unit-test
  Domain:
    dependencies:
    - target: DataStore
    platform: iOS
    settings:
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/iOS
          INFOPLIST_FILE: Domain/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.Domain
          SWIFT_VERSION: 5.0
        Release:
          CODE_SIGN_STYLE: Automatic
          FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/iOS
          INFOPLIST_FILE: Domain/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.Domain
          SWIFT_VERSION: 5.0
    sources: [Domain]
    type: framework
  DomainTests:
    dependencies:
    - target: Domain
    - target: RoyaleApp
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: DomainTests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.DomainTests
          SWIFT_VERSION: 5.0
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/RoyaleApp.app/RoyaleApp
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: DomainTests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.DomainTests
          SWIFT_VERSION: 5.0
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/RoyaleApp.app/RoyaleApp
    sources: [DomainTests]
    type: bundle.unit-test
  Presentation:
    dependencies:
    - target: Analytics
    - framework: Carthage/Build/iOS/Charts.framework
    - target: Domain
    - framework: Carthage/Build/iOS/Kingfisher.framework
    - framework: Carthage/Build/iOS/SwipeableTabBarController.framework
    platform: iOS
    settings:
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/iOS
          INFOPLIST_FILE: Presentation/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.Presentation
          SWIFT_VERSION: 5.0
        Release:
          CODE_SIGN_STYLE: Automatic
          FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/Carthage/Build/iOS
          INFOPLIST_FILE: Presentation/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.Presentation
          SWIFT_VERSION: 5.0
    sources: [Presentation]
    type: framework
  PresentationTests:
    dependencies:
    - target: Presentation
    - target: RoyaleApp
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: PresentationTests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.PresentationTests
          SWIFT_VERSION: 5.0
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/RoyaleApp.app/RoyaleApp
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: PresentationTests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.PresentationTests
          SWIFT_VERSION: 5.0
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/RoyaleApp.app/RoyaleApp
    sources: [PresentationTests]
    type: bundle.unit-test
  RoyaleApp:
    dependencies:
    - target: DataStore
    - target: Presentation
    - target: Domain
    - target: Analytics
    platform: iOS
    postbuildScripts:
    - name: Run SwiftLint
      runOnlyWhenInstalling: false
      script: "if which mint >/dev/null; then\n  mint run swiftlint swiftlint autocorrect
        --format\n  mint run swiftlint swiftlint\nelse\n  echo \"warning: Mint not
        installed, download from https://github.com/yonaskolb/Mint\"\nfi\n"
      shell: /bin/sh
    - inputFiles:
      - $(SRCROOT)/Carthage/Build/iOS/Alamofire.framework
      - $(SRCROOT)/Carthage/Build/iOS/SwipeableTabBarController.framework
      - $(SRCROOT)/Carthage/Build/iOS/Realm.framework
      - $(SRCROOT)/Carthage/Build/iOS/RealmSwift.framework
      - $(SRCROOT)/Carthage/Build/iOS/Charts.framework
      - $(SRCROOT)/Carthage/Build/iOS/Kingfisher.framework
      name: Carthage
      outputFiles:
      - '$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Alamofire.framework

        '
      - $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/SwipableTabBarController.framework
      - $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Realm.framework
      - $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/RealmSwift.framework
      - $(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Charts.framework
      runOnlyWhenInstalling: false
      script: 'mint run Carthage/Carthage carthage copy-frameworks

        '
      shell: /bin/sh
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 8CBGKNYH9U
          INFOPLIST_FILE: RoyaleApp/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.RoyaleApp
          SWIFT_VERSION: 5.0
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: 8CBGKNYH9U
          INFOPLIST_FILE: RoyaleApp/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.0
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.RoyaleApp
          SWIFT_VERSION: 5.0
    sources: [RoyaleApp]
    type: application
  RoyaleAppTests:
    dependencies:
    - target: RoyaleApp
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: RoyaleAppTests/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.4
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.RoyaleAppTests
          SWIFT_VERSION: 5.0
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/RoyaleApp.app/RoyaleApp
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: RoyaleAppTests/Info.plist
          IPHONEOS_DEPLOYMENT_TARGET: 13.4
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.RoyaleAppTests
          SWIFT_VERSION: 5.0
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/RoyaleApp.app/RoyaleApp
    sources: [RoyaleAppTests]
    type: bundle.unit-test
  RoyaleAppUITests:
    dependencies:
    - target: RoyaleApp
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: RoyaleAppUITests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.RoyaleAppUITests
          SWIFT_VERSION: 5.0
          TEST_TARGET_NAME: RoyaleApp
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
          CODE_SIGN_STYLE: Automatic
          INFOPLIST_FILE: RoyaleAppUITests/Info.plist
          PRODUCT_BUNDLE_IDENTIFIER: nakandakari.toru.RoyaleAppUITests
          SWIFT_VERSION: 5.0
          TEST_TARGET_NAME: RoyaleApp
    sources: [RoyaleAppUITests]
    type: bundle.ui-testing
schemes:
  RoyaleApp:
    build:
      targets:
        RoyaleApp: all
    run:
      config: Debug
      commandLineArguments:
        "-FIRDebugEnabled": false
        "-FIRDebugDisabled": true
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release